### ISSUE TITLE
Unhealthy containers when service.yaml does not override some parameters which are expected to provide default values in aea-config.yaml

### ISSUE THREAD

**Issue by jmoreira-valory** [valory-xyz/open-autonomy#1872]
Update: Following the guide https://docs.autonolas.network/open-autonomy/deployment/on-chain_deployment_checklist/, this might not be an issue, but certainly it can be confusing.

### Subject of the issue

Suppose that SERVICE-1 has the following `service.yaml`:

```
name: your_service
author: your_name
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha
number_of_agents: 4
---
public_id: valory/hello_world_abci:0.1.0
type: skill
models:
  params:
    args:
      service_registry_address: null
      share_tm_config_on_startup: false
      on_chain_service_id: null
      setup:
        all_participants:
        - - '0x0000000000000000000000000000000000000000'
        safe_contract_address:
        - '0x0000000000000000000000000000000000000000'
        consensus_threshold:
        - null
      hello_world_message: ${HELLO_WORLD_STRING_0:str:HELLO_WORLD! (from Agent 0)}
  benchmark_tool:
    args:
      log_dir: /benchmarks
```
**This works well.** 

Now, for SERVICE-2, assume that we remove the skill override , *and we expect that the default values of are taken from the `aea-config.yaml`*:

```
name: your_service
author: your_name
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeic3czcb7fpzru3fl4noxdwgwyzirqk6cqh763h6aio7ugl6qm5gha
number_of_agents: 4
```

If we inspect the **`aea-config.yaml`**, however, we see that **all_participants** and **safe_contract_address** do not provide these default values. Therefore, the developer is forced to include the override in the service.yaml config file (at least for these parameters):

```
---
public_id: valory/hello_world_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  params:
    args:
      hello_world_message: ${str:HELLO_WORLD!}
      service_registry_address: ${str:null}
      share_tm_config_on_startup: ${bool:false}
      on_chain_service_id: ${int:null}
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${list:[]}
        consensus_threshold: ${list:[null]}
      tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
      tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
```
Indeed, running SERVICE-2 as depicted above causes **at a very late stage** the infamous 

```
ERROR: for node3  Container "257af334450d" is unhealthy.

ERROR: for node0  Container "d4b46c0a6733" is unhealthy.

ERROR: for node1  Container "f9b8fe1c645e" is unhealthy.

ERROR: for node2  Container "6b4ad7c94ab8" is unhealthy.
```

when `autonomy deploy run` is called.

**This is especially disconcerting and frustrating for the developer, because the underlying cause of the issue is not evident when the issue appears.**

### Your environment
- Python version: [e.g. 3.7.2]
- Package Version [e.g. 0.1.3]
- Anything else you consider helpful.

### Steps to reproduce
Usual steps for each service:

```
autonomy hash all
autonomy push-all
autonomy fetch
autonomy build-image
autonomy deploy build
autonomy deploy run
```

### Expected behaviour

SERVICE-2 should be deployed without issue.

IMO, Default configuration for agents should ensure that a service can be run without the need of mandatory overrides. I agree this is not always possible (e.g., we have to specify the data provider for oracles, etc.) But it should be the case for "simple" agents like the demo agent. 

In this case the fix is easy. Should also open an independent ticket to review the case for other agents.

If this solution is not possible, this problem should be detected earlier and provide more informative messages to the user, rather than throwing an exception without clear information.

### Actual behaviour
See above.
