### ISSUE TITLE
Mount persistent volumes

### ISSUE THREAD

**Issue by 8ball030** [valory-xyz/open-autonomy#2082]
At present, there is no easy way to mount a build to a persistent volume.

Would be great to be able to do so;

(ideally using a similar syntax to Kubernetes, such that persistnt volumes cna easily be mounted as part of a spec).

Please see;

```
apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    hostPath:
      path: /any/path/it/will/be/replaced
  containers:
  - name: pv-recycler
    image: "registry.k8s.io/busybox"
    command: ["/bin/sh", "-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
    volumeMounts:
    - name: vol
      mountPath: /scrub
```

In the deployment (for kube) we need to pass;

```
mountpath 
storageClassName (default can be "")
vol_name
```

For for docker-compose, need to be able to pass a host path.

Would be cool to have an array of volumes we can mount per agent.

**Comment by DavidMinarsch** [comment]
Closing as implemented.

Persistent volume mounts are configurable per agent via `deployment_config.agent.volumes` in `service.yaml` (mapping of host directory to container mount path), and the setting flows through both backends:

- **docker-compose** (`autonomy/deploy/generators/docker_compose/base.py:203-206`): `extra_volumes` dict is emitted as `-  {host}:{container}:Z` entries under each agent service.
- **kubernetes** (`autonomy/deploy/generators/kubernetes/base.py:105-108, 158-161` + `templates.py`): the same dict is materialised as `PersistentVolumeClaim` + `volumeMounts` per pod.

Example `service.yaml`:

```yaml
deployment_config:
  agent:
    volumes:
      ./my_local_data: /app/data
```

The requested richer shape (`{mountPath, vol_name, storageClassName}`) was simplified to the `{host: container}` dict, which covers the stated use cases on both backends.
